# Generated by Django 5.2.8 on 2025-12-08 07:22

import api.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(help_text='Unique Org ID', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('COORDINATOR', 'Coordinator/Manager'), ('COMMITTEE', 'Committee'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=20)),
                ('employee_dept', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_role', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_name', models.CharField(blank=True, help_text='Reporting Manager', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Coordinator Approved'), ('COMMITTEE_APPROVED', 'Finalist'), ('AWARDED', 'Winner'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('nominator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_made', to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nominator',)},
            },
        ),
    ]
