# Generated by Django 5.2.8 on 2025-12-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('COORDINATOR', 'Coordinator/Manager'), ('COMMITTEE', 'Committee'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
