# Generated by Django 5.2.8 on 2025-12-09 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.nomination')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_cast', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
