# Generated by Django 5.2.8 on 2025-12-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nomination_nominator_name_nomination_nominee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Reporting Manager', max_length=100, null=True),
        ),
    ]
