# Generated by Django 5.2.8 on 2025-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_nomination_status_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Coordinator Approved'), ('COMMITTEE_APPROVED', 'Finalist'), ('AWARDED', 'Winner'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
